
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EC_Assignment2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    public Category()
    {

        this.Accounts = new HashSet<Account>();

    }


    public int CategoryID { get; set; }

    public string CategoryName { get; set; }

    public bool isExpense { get; set; }

    public bool isActive { get; set; }



    public virtual ICollection<Account> Accounts { get; set; }

}

}
